---
# defaults file for ansible_role_libvirt_client_configure
ansible_role_libvirt_client_configure_adminuser: myadmin
ansible_role_libvirt_client_configure_journald_system_max_use: 4G
ansible_role_libvirt_client_configure_journald_system_max_file_size: 500M
