---
# defaults file for ansible_role_libvirt_client_configure
ansible_role_libvirt_client_configure_adminuser: myadmin
ansible_role_libvirt_client_configure_vm_count: 1
ansible_role_libvirt_client_configure_vm_domain: "jobjects.org"
ansible_role_libvirt_client_configure_vm_domain_ip_pattern: "192.168.56.14"
ansible_role_libvirt_client_configure_journald_system_max_use: 4G
ansible_role_libvirt_client_configure_journald_system_max_file_size: 500M
